seed: 42
device: 'cuda'

data:
  dataset_name: fastMRI_knee
  image_size: 320
  R: 4
  mask_type: equispace_diffusion  # 修改为 'dense' 或 'linear' 或 'sparse'
  center_fraction: 0.08
  patch_size: 4
  seed: 42


  combine_coil: true

  # 建议训练时先保持和你之前一致；如果你想全切片训练再改成 0
  num_skip_slice: 5

  normalize_type: minmax
  normalize_coeff: 1.0
  num_workers: 8

  # ========= kspace 路径 =========
  data_root: /mnt/SSD/wsy/projects/HFS-SDE-master/data/multicoil_train_knee/kspace
  test_root: /mnt/SSD/wsy/projects/HFS-SDE-master/data/multicoil_test/kspace
  val_root: /mnt/SSD/wsy/projects/HFS-SDE-master/data/multicoil_test/kspace

  # 可选：快速 debug 时可手动改成 val
  # test_root: /mnt/SSD/wsy/projects/HFS-SDE-master/data/multicoil_val/kspace
  #sample_root: /mnt/SSD/wsy/projects/HFS-SDE-master/data/multicoil_val/kspace

  # ========= maps 根目录 =========
  # 注意：这里填总目录，不是具体某个 maps 子文件夹
  maps_root: /mnt/SSD/wsy/projects/HFS-SDE-master/data
  map_key: s_maps

model:
  backbone: swin_dits
  patch_size: 4
  hidden_size: 384
  depth: 8
  num_heads: 8
  window_size: 8
  mlp_ratio: 4.0
  residual: False

training:
  timesteps: 19
  loss_type: l1
  batch_size: 8
  #lambda_dc: 1
  lr: 5e-5
  train_num_steps: 7000
  gradient_accumulate_every: 1
  fp16: False
  ema_decay: 0.995
  step_start_ema: 700
  update_ema_every: 10
  save_and_sample_every: 200
  results_folder: './results_filterdiff_swin_5e-5'
  filter_schedule_type: dense
  center_core_size: 26
  use_explicit_dc: True

  val_every: 200
  early_stop_patience: 8
  early_stop_min_delta: 0.005
  monitor_metric: psnr