seed: 42
device: 'cuda'

data:
  dataset_name: fastMRI_knee
  image_size: 320
  R: 4
  seed: 42

  center_fraction: 0.075
  patch_size: 4
  combine_coil: true
  acq_mask_path: /mnt/SSD/wsy/projects/filter_diffusion/mask/uniform_acc4_acs24.mat
  acq_mask_key: mask
  acq_mask_fold_path: null
  acq_mask_fold_key: mask_fold

  # 建议训练时先保持和你之前一致；如果你想全切片训练再改成 0
  num_skip_slice: 6
  normalize_coeff: 1.0
  num_workers: 2

  # ========= kspace 路径 =========
  data_root: /mnt/SSD/wsy/projects/HFS-SDE-master/data/multicoil_train_knee/kspace
 #test_root: /mnt/SSD/wsy/projects/HFS-SDE-master/data/multicoil_test/kspace
 #val_root: /mnt/SSD/wsy/projects/HFS-SDE-master/data/multicoil_test/kspace

  # 可选：快速 debug 时可手动改成 val
  test_root: /mnt/SSD/wsy/projects/HFS-SDE-master/data/multicoil_val/kspace
  val_root: /mnt/SSD/wsy/projects/HFS-SDE-master/data/multicoil_val/kspace

  # ========= maps 根目录 =========
  # 注意：这里填总目录，不是具体某个 maps 子文件夹
  maps_root: /mnt/SSD/wsy/projects/HFS-SDE-master/data
  map_key: s_maps

model:
  backbone: swin_dits
  patch_size: 4
  hidden_size: 192
  depth: 4
  num_heads: 4
  window_size: 8
  mlp_ratio: 4.0


training:
  timesteps: 19
  loss_type: l1
  batch_size: 1
  lr: 1e-5
  train_num_steps: 5000
  gradient_accumulate_every: 1
  fp16: False
  ema_decay: 0.995
  step_start_ema: 2000
  update_ema_every: 1
  save_and_sample_every: 100
  results_folder: './results_debug'
  filter_schedule_type: dense
  center_core_size: 24 #filter end
  max_val_batches: 20
  val_every: 100
  early_stop_patience: 10000
  early_stop_min_delta: 0.0000001
  monitor_metric: psnr
  image_loss_mode: complex
  lr_scheduler_type: none
  warmup_steps: 0
  min_lr: 0
  input_representation: kspace_raw   # 推荐先用这个
  lambda_img: 100